name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build mod
        working-directory: ClientElytraVisual_1.21.11
        run: gradle build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: ClientElytraVisual_1.21.11/build/libs/*.jar
